# Generated by Django 4.2.2 on 2023-06-08 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_rename_date_announcement_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='datetime',
            new_name='publication_datetime',
        ),
    ]
