# Generated by Django 4.2.2 on 2023-06-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_remove_announcement_category_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='category',
        ),
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.ManyToManyField(to='board.category', verbose_name='Категория'),
        ),
    ]
