# Generated by Django 4.2.2 on 2023-06-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_announcement_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='snippet',
            field=models.CharField(max_length=255),
        ),
    ]
