# Generated by Django 4.2.2 on 2023-06-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_rename_datetime_announcement_publication_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Заголовок')),
            ],
        ),
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.ManyToManyField(to='board.category', verbose_name='Категория'),
        ),
    ]
