# Generated by Django 4.2.2 on 2023-06-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_category_announcement_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='category',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.CharField(default='some category', max_length=255, verbose_name='Название категории'),
        ),
    ]
