# Generated by Django 4.2.2 on 2023-06-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='body',
        ),
        migrations.AddField(
            model_name='response',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
