# Generated by Django 4.2.2 on 2023-06-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_user_photo_profile_vk_url_profile_ws_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Немного о себе ...'),
        ),
    ]
